##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=+camlp4
CAMLP4:=/home/notin/exec/ocaml-3.09.3/bin/camlp4
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=/home/notin/exec/ocaml-3.09.3/bin/ocamlc -rectypes -c
CAMLOPTC:=/home/notin/exec/ocaml-3.09.3/bin/ocamlopt -c
CAMLLINK:=/home/notin/exec/ocaml-3.09.3/bin/ocamlc
CAMLOPTLINK:=/home/notin/exec/ocaml-3.09.3/bin/ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:=-R . algebra
COQDOCLIBS:=-R . algebra

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=Abelian_group_cat.v\
  Abelian_group_facts.v\
  Algebra_facts.v\
  Algebra.v\
  Cantor_Bernstein.v\
  Cartesian.v\
  Categories2.v\
  Categories.v\
  Cfield_cat.v\
  Cfield_facts.v\
  Complex_field.v\
  Diff.v\
  Endo_set.v\
  Field_cat.v\
  Field_facts.v\
  Fmap.v\
  Fpart2.v\
  Fpart.v\
  Fraction_field.v\
  Free_abelian_group.v\
  Free_abelian_monoid.v\
  Free_group.v\
  Free_module.v\
  Free_monoid.v\
  Generated_group.v\
  Generated_module.v\
  Generated_monoid.v\
  Group_cat.v\
  Group_facts.v\
  Group_hom_factor.v\
  Group_kernel.v\
  Group_of_group_hom.v\
  Group_power.v\
  Group_quotient.v\
  Group_util.v\
  Hom_module.v\
  Ideal.v\
  Integral_domain_cat.v\
  Integral_domain_facts.v\
  Inter.v\
  Module_cat.v\
  Module_facts.v\
  Module_kernel.v\
  Module_util.v\
  Monoid_cat.v\
  Monoid_facts.v\
  Monoid_kernel.v\
  Monoid_util.v\
  Operation_of_monoid.v\
  Parts2.v\
  Parts3.v\
  Parts.v\
  Qfield.v\
  Ring_cat.v\
  Ring_facts.v\
  Ring_util.v\
  Set_cat.v\
  Sets.v\
  Sgroup_cat.v\
  Sgroup_facts.v\
  Singleton.v\
  Subcat.v\
  Sub_group.v\
  Sub_module.v\
  Sub_monoid.v\
  Sub_sgroup.v\
  Tiroirs.v\
  Union.v\
  Z_group_facts.v\
  Z_group.v\
  Zring.v\
  ZUP.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: Abelian_group_cat.vo\
  Abelian_group_facts.vo\
  Algebra_facts.vo\
  Algebra.vo\
  Cantor_Bernstein.vo\
  Cartesian.vo\
  Categories2.vo\
  Categories.vo\
  Cfield_cat.vo\
  Cfield_facts.vo\
  Complex_field.vo\
  Diff.vo\
  Endo_set.vo\
  Field_cat.vo\
  Field_facts.vo\
  Fmap.vo\
  Fpart2.vo\
  Fpart.vo\
  Fraction_field.vo\
  Free_abelian_group.vo\
  Free_abelian_monoid.vo\
  Free_group.vo\
  Free_module.vo\
  Free_monoid.vo\
  Generated_group.vo\
  Generated_module.vo\
  Generated_monoid.vo\
  Group_cat.vo\
  Group_facts.vo\
  Group_hom_factor.vo\
  Group_kernel.vo\
  Group_of_group_hom.vo\
  Group_power.vo\
  Group_quotient.vo\
  Group_util.vo\
  Hom_module.vo\
  Ideal.vo\
  Integral_domain_cat.vo\
  Integral_domain_facts.vo\
  Inter.vo\
  Module_cat.vo\
  Module_facts.vo\
  Module_kernel.vo\
  Module_util.vo\
  Monoid_cat.vo\
  Monoid_facts.vo\
  Monoid_kernel.vo\
  Monoid_util.vo\
  Operation_of_monoid.vo\
  Parts2.vo\
  Parts3.vo\
  Parts.vo\
  Qfield.vo\
  Ring_cat.vo\
  Ring_facts.vo\
  Ring_util.vo\
  Set_cat.vo\
  Sets.vo\
  Sgroup_cat.vo\
  Sgroup_facts.vo\
  Singleton.vo\
  Subcat.vo\
  Sub_group.vo\
  Sub_module.vo\
  Sub_monoid.vo\
  Sub_sgroup.vo\
  Tiroirs.vo\
  Union.vo\
  Z_group_facts.vo\
  Z_group.vo\
  Zring.vo\
  ZUP.vo

spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

.SUFFIXES: .v .vo .vi .g .html .tex .g.tex .g.html

%.vo %.glob: %.v
	$(COQC) $(COQLIBS) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d.raw: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@"\
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.d: %.v.d.raw
	$(HIDE)sed 's/\(.*\)\.vo[[:space:]]*:/\1.vo \1.glob:/' < "$<" > "$@" \
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

